### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yamazakitakuya1115** [yamazakitakuya1115/furima-30547#11]
最終課題の挙動確認をお願いいたします。

URL
https://furima-30547.herokuapp.com/

Basic認証
ID　admin
pass　3333

出品者用アカウント
ichiro@sample.com
1a1a1a

購入者用アカウント
jiro@sample.com
1a1a1a

購入者用カード
番号　4242424242424242
期限　1月23年
セキュリティコード　123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。

**Comment by yamazakitakuya1115** [comment]
ありがとうございます！！m(_ _)m
